name: Deploy to VSCode marketplace

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'

    - name: Check release version matches package.json
      run: node ./.github/bin/check-package-version ${{ github.ref }}

    - name: Publish to VSCode Marketplace
      env:
        PAT: ${{ secrets.MARKETPLACE_PAT }}
      run: npx @vscode/vsce publish -p "$PAT"

    - name: Delete tag on failure
      if: failure()
      run: |
        git push origin :${{ github.ref }}
        echo "::error::The GitHub release has been relegated to a draft and can be republished when the problems are fixed"
